package com.papi.player.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.papi.player.javabean.VideoBean;
import com.papi.player.javabean.MediaBean;

import com.papi.player.greendao.VideoBeanDao;
import com.papi.player.greendao.MediaBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig videoBeanDaoConfig;
    private final DaoConfig mediaBeanDaoConfig;

    private final VideoBeanDao videoBeanDao;
    private final MediaBeanDao mediaBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        videoBeanDaoConfig = daoConfigMap.get(VideoBeanDao.class).clone();
        videoBeanDaoConfig.initIdentityScope(type);

        mediaBeanDaoConfig = daoConfigMap.get(MediaBeanDao.class).clone();
        mediaBeanDaoConfig.initIdentityScope(type);

        videoBeanDao = new VideoBeanDao(videoBeanDaoConfig, this);
        mediaBeanDao = new MediaBeanDao(mediaBeanDaoConfig, this);

        registerDao(VideoBean.class, videoBeanDao);
        registerDao(MediaBean.class, mediaBeanDao);
    }
    
    public void clear() {
        videoBeanDaoConfig.getIdentityScope().clear();
        mediaBeanDaoConfig.getIdentityScope().clear();
    }

    public VideoBeanDao getVideoBeanDao() {
        return videoBeanDao;
    }

    public MediaBeanDao getMediaBeanDao() {
        return mediaBeanDao;
    }

}
