package com.papi.player.javabean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MediaBean".
 */
public class MediaBean {

    private String enter_id;
    private String cover_url;
    private String name;
    private String time;
    private String cId;
    private String cCode;

    public MediaBean() {
    }

    public MediaBean(String enter_id) {
        this.enter_id = enter_id;
    }

    public MediaBean(String enter_id, String cover_url, String name, String time, String cId, String cCode) {
        this.enter_id = enter_id;
        this.cover_url = cover_url;
        this.name = name;
        this.time = time;
        this.cId = cId;
        this.cCode = cCode;
    }

    public String getEnter_id() {
        return enter_id;
    }

    public void setEnter_id(String enter_id) {
        this.enter_id = enter_id;
    }

    public String getCover_url() {
        return cover_url;
    }

    public void setCover_url(String cover_url) {
        this.cover_url = cover_url;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getCId() {
        return cId;
    }

    public void setCId(String cId) {
        this.cId = cId;
    }

    public String getCCode() {
        return cCode;
    }

    public void setCCode(String cCode) {
        this.cCode = cCode;
    }

}
