package com.papi.player.javabean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "VideoBean".
 */
public class VideoBean {

    private String cover_url;
    private String enter_id;
    private String cId;
    private String cCode;
    private String name;
    private String time;

    public VideoBean() {
    }

    public VideoBean(String enter_id) {
        this.enter_id = enter_id;
    }

    public VideoBean(String cover_url, String enter_id, String cId, String cCode, String name, String time) {
        this.cover_url = cover_url;
        this.enter_id = enter_id;
        this.cId = cId;
        this.cCode = cCode;
        this.name = name;
        this.time = time;
    }

    public String getCover_url() {
        return cover_url;
    }

    public void setCover_url(String cover_url) {
        this.cover_url = cover_url;
    }

    public String getEnter_id() {
        return enter_id;
    }

    public void setEnter_id(String enter_id) {
        this.enter_id = enter_id;
    }

    public String getCId() {
        return cId;
    }

    public void setCId(String cId) {
        this.cId = cId;
    }

    public String getCCode() {
        return cCode;
    }

    public void setCCode(String cCode) {
        this.cCode = cCode;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

}
